### ISSUE TITLE
systray please

### ISSUE THREAD

**Issue by adrian-gluu** [LukeSmithxyz/dwm#83] opened 2020-06-06 08:24 UTC
Hey Luke, please can you add systray support to your dwm build, I love your dwm desktop am using it and following everything you talk about dwm and i love it, but for work i need systray beause my work apps need it like rocket.chat riot.im need systray notificacions when I get work msg from my co-workers, please can you add systray patch to your build, I saw in your videos you have the path download it but can please please apply it?

Thanks for all ur hard work with DWM is fantastic

**Comment by LukeSmithxyz** [comment] 2020-06-06 10:51
Duplicate of https://github.com/LukeSmithxyz/dwm/pull/50 https://github.com/LukeSmithxyz/dwm/pull/61 https://github.com/LukeSmithxyz/dwm/pull/35 https://github.com/LukeSmithxyz/dwm/issues/8 https://github.com/LukeSmithxyz/dwm/issues/37 and the last time you opened this: https://github.com/LukeSmithxyz/dwm/issues/46.

If you want it, apply the patch which has already been written for you. It will not be in this build. Don't ask again.

**Closed as completed by LukeSmithxyz** 2020-06-06 10:51 UTC

**Comment by adrian-gluu** [comment] 2020-06-06 18:20
the patch for systray didnt work on ur build
