### ISSUE TITLE
systray patch

### ISSUE THREAD

**Issue by adrian-gluu** [LukeSmithxyz/dwm#46] opened 2020-04-27 21:32 UTC
tried to apply this patch: https://dwm.suckless.org/patches/systray/
but didnt apply can you add systray to your dwm build?

**Comment by LukeSmithxyz** [comment] 2020-04-27 21:59
Duplicate of https://github.com/LukeSmithxyz/dwm/issues/34.

**Closed as completed by LukeSmithxyz** 2020-04-27 21:59 UTC
